# OpenID Connect (OIDC) configuration for the app
# Available as `Rails.application.config_for(:oidc)`
#
# ⚠ Do *not* store secrets here!! The entire contents of this file is
# available to anyone who issues an unauthenticated GET to
# `/oidc/config` (see
# ../app/controllers/OIDC/frontend_config_controller.rb)
development:
  serverUrl: <%= ENV.fetch("OIDC_SERVER_URL") { "http://localhost:8080" } %>
  realm: <%= ENV.fetch("OIDC_REALM_ID") { "rails" } %>
